config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'books/admin'
  get 'books/patron'
  get 'books/review'
  get '/checkout/', to: "books#checkout"


  resources :admin_searches
  resources :patron_searches
  # post  'adminsearches/new'
  # post  'patronsearch/new'

  resources	:books do
    resources :reviews
  end

  root 'welcome#index'

  #get 'books/search'
  #post 'books/search'
  #get 'books/result'

  get '/reviews/new', to: 'reviews#new'
end

app/models/admin_search.rb
class AdminSearch < ApplicationRecord
  def adminsearch_books
    books = Book.all
    books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "%#{isbn}%", "%#{title}%", "%#{author}%")
    # books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "#{isbn}", "#{title}", "#{author}")
    return books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates	:title,	presence:	true
  validates :author, presence: true
  validates :copies, presence: true, numericality: { only_integer: true }
  validates :isbn, presence: true, numericality: { only_integer: true }
  validates_format_of :isbn, :with => /[0-9]{10}/
  validates_length_of :isbn, maximum: 10
  validates_uniqueness_of :isbn

  def self.adminsearch(title,author,isbn)
    if adminsearch
      where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "%#{isbn}%", "%#{title}%", "%#{author}%")
      # where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "#{isbn}", "#{title}", "#{author}")
    end
  end

  def checkout
    self.copies-=1
    #redirect_to new_admin_search_path
  end
end

app/models/patron_search.rb
class PatronSearch < ApplicationRecord
  def patronsearch_books
    books = Book.all
    books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "%#{isbn}%", "%#{title}%", "%#{author}%")
    # books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "#{isbn}", "#{title}", "#{author}")
    return books
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/models/search.rb
class Search < ApplicationRecord

  def search_books
    books = Book.all
    books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "%#{isbn}%", "%#{title}%", "%#{author}%")
    # books = books.where("isbn LIKE ? and title LIKE ? and author LIKE ? ", "#{isbn}", "#{title}", "#{author}")
    return books
  end
end

app/controllers/admin_searches_controller.rb
class AdminSearchesController < ApplicationController
  def new
    @admin_search = AdminSearch.new
  end

  def create
    @admin_search = AdminSearch.create(search_params)
    redirect_to @admin_search
  end

  def show
    @admin_search = AdminSearch.find(params[:id])
  end

  private
  def search_params
    params.require(:admin_search).permit(:title, :author, :isbn)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  # def index
  #   @books = Book.all
  # end

  def create
    @book = Book.new(params.require(:book).permit(:title, :author, :isbn, :copies))
    if @book.save
      redirect_to welcome_index_path
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(params.require(:book).permit(:title, :author, :isbn, :copies))
      redirect_to new_admin_search_path
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def index
    if params[:search]
      empty_search = params[:search].keep_if {|k, val| !val.blank?}.empty?
    else
      empty_search = true
    end
    if empty_search
     # no search was submitted, or search params are all blank
     @books = ""
    else
     # a search was submitted
     @books = Book.search(params[:search])
    end
  end

  # def search
  #   @books = Book.where("title LIKE ?", "%#{params[:search]}%")
  # end

  def checkout
    @book = Book.find(params[:id])
    if @book.copies > 0
      @book.checkout
      @book.save!
      redirect_to new_admin_search_path
    else
      flash.alert = 'The book has less than 1 copy left.'
    end
  end

end

app/controllers/patron_searches_controller.rb
class PatronSearchesController < ApplicationController
  def new
    @patron_search = PatronSearch.new
  end

  def create
    @patron_search = PatronSearch.create(search_params)
    redirect_to @patron_search
  end

  def show
    @patron_search = PatronSearch.find(params[:id])
  end

  private
  def search_params
    params.require(:patron_search).permit(:title, :author, :isbn)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end
  def index
    @review = Review.all
  end
  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.create(params.require(:review).permit(:name, :body))
    redirect_to book_path(@book)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:title, :author, :isbn)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_searches_helper.rb
module AdminSearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/patron_searches_helper.rb
module PatronSearchesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_searches/new.html.erb
<h1>Search for books</h1>

<%=	form_with(model: @admin_search, local:	true)	do	|form|	%>

  <p>
    <%=	form.label :title %><br>
    <%=	form.text_field:title %>
  </p>

  <p>
    <%=	form.label :author %><br>
    <%=	form.text_field :author %>
  </p>

  <p>
    <%=	form.label :isbn %><br>
    <%=	form.text_field :isbn %>
  </p>

  <p>
    <%=	form.submit "Search"%>
  </p>

<% end %>


<%=	link_to 'Back',	welcome_index_path %>

app/views/admin_searches/show.html.erb
<h1>Searching Result</h1>

<% if @admin_search.adminsearch_books.empty? %>
  <p>No Records Found</p>
<% else %>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>ISBN</th>
    <th>Copies</th>
    <th></th>
  </tr>

  <%	@admin_search.adminsearch_books.each do	|book|	%>
    <tr>
      <td><%=	book.title %></td>
      <td><%=	book.author %></td>
      <td><%=	book.isbn %></td>
      <td><%=	book.copies %></td>
      <td><%=	link_to 'Edit', edit_book_path(book)	%></td>
      <% if (book.copies > 0) %>
        <td><%=	link_to 'Checkout', checkout_path(:id => book.id)	%></td>
      <%	end	%>
    </tr>
  <%	end	%>
</table>
<% end %>
<%= link_to "Back", welcome_index_path %>

app/views/books/admin.html.erb
<h1>Hello Admin</h1>
<%=	link_to 'Add Book', new_book_path %>
<%= link_to 'Search book', new_admin_search_path %>

app/views/books/edit.html.erb
<%=	form_with(model: @book, local:	true)	do	|form|	%>

  <%	if @book.errors.any?	%>
    <div	id="error_explanation">
      <h2>
        error/s	prohibited
        this book from being saved:
      </h2>
      <ul>
        <%	@book.errors.full_messages.each do	|msg|	%>
          <li><%=	msg %></li>
        <%	end	%>
      </ul>
    </div>
  <%	end	%>

  <p>
    <%=	form.label :title %><br>
    <%=	form.text_field:title %>
  </p>

  <p>
    <%=	form.label :author %><br>
    <%=	form.text_field :author %>
  </p>

  <p>
    <%=	form.label :isbn %><br>
    <%=	form.text_field :isbn %>
  </p>

  <p>
    <%=	form.label :copies %><br>
    <%=	form.text_field :copies %>
  </p>

  <p>
    <%=	form.submit %>
  </p>
<%	end	%>
<%=	link_to 'Back',	new_admin_search_path %>

app/views/books/index.html.erb
<h2>Reviews</h2>
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>
 

<% end %>

app/views/books/new.html.erb
<%=	form_with scope:	:book,	url: books_path, local:	true	do	|form|	%>

  <%	if @book.errors.any?	%>
    <div	id="error_explanation">
      <h2>
        error/s	prohibited
        this book from being saved:
      </h2>
      <ul>
        <%	@book.errors.full_messages.each do	|msg|	%>
          <li><%=	msg %></li>
        <%	end	%>
      </ul>
    </div>
  <%	end	%>

  <p>
    <%=	form.label :title %><br>
    <%=	form.text_field:title %>
  </p>

  <p>
    <%=	form.label :author %><br>
    <%=	form.text_field :author %>
  </p>

  <p>
    <%=	form.label :isbn %><br>
    <%=	form.text_field :isbn %>
  </p>

  <p>
    <%=	form.label :copies %><br>
    <%=	form.text_field :copies %>
  </p>

  <p>
    <%=	form.submit %>
  </p>
<%	end	%>
<%=	link_to 'Back',	welcome_index_path %>

app/views/books/patron.html.erb
<h1>Hello Patron</h1>
<%= link_to 'Search book', new_patron_search_path %>

app/views/books/result.html.erb
<h1>Search Results</h1>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Copies:</strong>
  <%= @book.copies %>
</p>

<h2>Reviews</h2>
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>
  <%= link_to 'Destroy Review', [review.book, review], method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

<h2>Add	 a review:</h2>
<%=	form_with(model: [ @book,	@book.reviews.build ],	local:	true)	do	|form|	%>
  <p>
    <%=	form.label :name	%><br>
    <%=	form.text_field :name	%>
  </p>
  <p>
    <%=	form.label :body	 %><br>
    <%=	form.text_area :body	%>
  </p>
  <p>
    <%=	form.submit %>
  </p>
<%	end	%>


    <%= link_to "Back", welcome_index_path %>

app/views/books/review.html.erb
<h2>Reviews</h2>
<div hidden> <%= @book = Book.find(params[:book_id]) %></div >
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>


<% end %>

app/views/books/search.html.erb
<h2>Reviews</h2>
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>

<% end %>

app/views/books/show.html.erb
<h2>Add	 a review:</h2>
<%=	form_with(model: [ @book, @book.reviews.build ], local: true)	do	|form|	%>
  <p>
    <%=	form.label :name	%><br>
    <%=	form.text_field :name	%>
  </p>
  <p>
    <%=	form.label :body	 %><br>
    <%=	form.text_area :body	%>
  </p>
  <p>
    <%=	form.submit %>
  </p>
<%	end	%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patron_searches/new.html.erb
<h1>Search for books</h1>

<%=	form_with(model: @patron_search, local:	true)	do	|form|	%>

  <p>
    <%=	form.label :title %><br>
    <%=	form.text_field:title %>
  </p>

  <p>
    <%=	form.label :author %><br>
    <%=	form.text_field :author %>
  </p>

  <p>
    <%=	form.label :isbn %><br>
    <%=	form.text_field :isbn %>
  </p>

  <p>
    <%=	form.submit "Search"%>
  </p>

<% end %>


<%=	link_to 'Back',	welcome_index_path %>

app/views/patron_searches/show.html.erb
<h1>Searching Result</h1>

<% if @patron_search.patronsearch_books.empty? %>
  <p>No Records Found</p>
<% else %>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>ISBN</th>
    <th>Copies</th>
    <th></th>
  </tr>

  <%	@patron_search.patronsearch_books.each do	|book|	%>
    <tr>
      <td><%=	book.title %></td>
      <td><%=	book.author %></td>
      <td><%=	book.isbn %></td>
      <td><%=	book.copies %></td>
      <td><%=	link_to 'Add Review', book_path(book)	%></td>
      <td><%=	link_to 'View Review', book_reviews_path(book)	%></td>
    </tr>
  <%	end	%>
</table>
<% end %>
<%= link_to "Back", welcome_index_path %>

app/views/reviews/index.html.erb
<h2>Reviews</h2>
<div hidden> <%= @book = Book.find(params[:book_id]) %></div >
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>


<% end %>

app/views/reviews/new.html.erb
<h2>Add	 a review:</h2>
<%=	form_with(model: [ @book, @book.reviews.build ], local: true)	do	|form|	%>
  <p>
    <%=	form.label :name	%><br>
    <%=	form.text_field :name	%>
  </p>
  <p>
    <%=	form.label :body	 %><br>
    <%=	form.text_area :body	%>
  </p>
  <p>
    <%=	form.submit %>
  </p>
<%	end	%>

app/views/reviews/show.html.erb
<h2>Reviews</h2>
<% @book.reviews.each do |review| %>
  <p>
    <strong>Name:</strong>
    <%= review.name %>
  </p>
 
  <p>
    <strong>Review:</strong>
    <%= review.body %>
  </p>

<% end %>

app/views/searches/new.html.erb
<h1>Search for books</h1>

<%=	form_with(model: @search, local:	true)	do	|form|	%>

  <p>
    <%=	form.label :title %><br>
    <%=	form.text_field:title %>
  </p>

  <p>
    <%=	form.label :author %><br>
    <%=	form.text_field :author %>
  </p>

  <p>
    <%=	form.label :isbn %><br>
    <%=	form.text_field :isbn %>
  </p>

  <p>
    <%=	form.submit "Search"%>
  </p>

<% end %>


<%=	link_to 'Back',	welcome_index_path %>

app/views/searches/show.html.erb
<h1>Searching Result</h1>

<% if @search.search_books.empty? %>
  <p>No Records Found</p>
<% else %>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>ISBN</th>
    <th>Copies</th>
    <th></th>
  </tr>

  <%	@search.search_books.each do	|book|	%>
    <tr>
      <td><%=	book.title %></td>
      <td><%=	book.author %></td>
      <td><%=	book.isbn %></td>
      <td><%=	book.copies %></td>
      <td><%=	link_to 'Edit', edit_book_path(book)	%></td>
    </tr>
  <%	end	%>
</table>
<% end %>
<%= link_to "Back", welcome_index_path %>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>
<%=	link_to 'Administrator', books_admin_path %>
<%= link_to 'Patron', books_patron_path %>